using './main.bicep'

param snInstanceUrl = ''
param snClientId = ''
param snClientSecret = ''
param snAuthFlow = 'client_credentials'
param snSlackIndexedTable = 'u_slack_content'
param azureClientId = ''
param azureClientSecret = ''
param connectorId = 'servicenow-slack'
param connectorName = 'ServiceNow Slack'
param connectorDescription = 'Slack messages and attachments from public channels indexed by ServiceNow AI Search'
