<#
.SYNOPSIS
    Tests a GitHub OAuth App's client ID and secret against the full
    authorization code flow used by Copilot Cowork.

.DESCRIPTION
    Reproduces exactly what the Microsoft Enterprise Token Store does when a
    user connects the GitHub connector:

      leg 1  authorize  -> GitHub redirects to the Teams redirect URI with a code
      leg 2  token      -> the code plus client_id/client_secret is exchanged

    Cowork reports both failures as one generic connector error. This script
    separates them and prints GitHub's actual error text.

    The client secret is read as a SecureString, is never echoed, and never
    leaves this machine. Nothing is written to disk.

.EXAMPLE
    .\Test-OAuthExchange.ps1
    .\Test-OAuthExchange.ps1 -ClientId Ov23liXXXXXXXXXXXXXX -Scope "repo read:org read:user"
#>

param(
    [string]$ClientId,
    [string]$Scope = "repo read:org read:user offline_access",
    [string]$RedirectUri = "https://teams.microsoft.com/api/platform/v1.0/oAuthRedirect",
    [switch]$NoBrowser
)

$ErrorActionPreference = "Stop"

if (-not $ClientId) { $ClientId = Read-Host "GitHub OAuth App Client ID" }
$secure = Read-Host "GitHub OAuth App Client Secret" -AsSecureString
$secret = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
    [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure))

if ([string]::IsNullOrWhiteSpace($secret)) { throw "No client secret provided." }
if ($secret -ne $secret.Trim()) {
    Write-Host "WARNING: the secret has leading or trailing whitespace. Trimming for this test," -ForegroundColor Yellow
    Write-Host "         but re-paste it in the Teams developer portal without the extra characters." -ForegroundColor Yellow
    $secret = $secret.Trim()
}

$state = [guid]::NewGuid().ToString("N")
$authorizeUrl = "https://github.com/login/oauth/authorize" +
    "?client_id=$([uri]::EscapeDataString($ClientId))" +
    "&redirect_uri=$([uri]::EscapeDataString($RedirectUri))" +
    "&scope=$([uri]::EscapeDataString($Scope))" +
    "&state=$state"

Write-Host ""
Write-Host "Leg 1 - authorize" -ForegroundColor Cyan
Write-Host "Opening GitHub in your browser. Sign in and approve."
Write-Host ""
Write-Host "EXPECTED: you will land on a teams.microsoft.com ERROR page saying something like" -ForegroundColor Yellow
Write-Host "  'Please contact the app owner to ensure the app is registered with the OAuth" -ForegroundColor Yellow
Write-Host "   provider and this client id is registered in the OAuth configuration.'" -ForegroundColor Yellow
Write-Host "That is normal and is NOT the failure being tested. Teams cannot resolve this" -ForegroundColor Yellow
Write-Host "callback because the state was generated by this script rather than by Teams." -ForegroundColor Yellow
Write-Host "This test only needs the 'code' value from that page's URL." -ForegroundColor Yellow
Write-Host ""
Write-Host "Copy the FULL URL from the address bar and paste it below. Codes expire in about" -ForegroundColor Cyan
Write-Host "10 minutes and are single-use, so paste it promptly." -ForegroundColor Cyan
Write-Host ""
Write-Host $authorizeUrl -ForegroundColor DarkGray
Write-Host ""
if ($NoBrowser) {
    Write-Host "-NoBrowser set: open the URL above yourself, in the browser profile that is" -ForegroundColor Cyan
    Write-Host "signed in to the correct GitHub account." -ForegroundColor Cyan
}
else {
    Start-Process $authorizeUrl
    Write-Host "If that opened the wrong browser profile, re-run with -NoBrowser and open the" -ForegroundColor DarkGray
    Write-Host "URL above manually instead." -ForegroundColor DarkGray
}

$redirected = Read-Host "Paste the full redirect URL"
if (-not $redirected) { throw "No URL provided." }

$q = @{}
foreach ($pair in (([uri]$redirected).Query.TrimStart('?') -split '&')) {
    if (-not $pair) { continue }
    $kv = $pair -split '=', 2
    $key = [uri]::UnescapeDataString($kv[0])
    $val = ''
    if ($kv.Count -gt 1) {
        $plusDecoded = $kv[1] -replace '\+', ' '
        $val = [uri]::UnescapeDataString($plusDecoded)
    }
    $q[$key] = $val
}
$code     = $q["code"]
$err      = $q["error"]
$errDesc  = $q["error_description"]
$gotState = $q["state"]

if ($err) {
    Write-Host ""
    Write-Host "LEG 1 FAILED - GitHub rejected the authorization request." -ForegroundColor Red
    Write-Host "  error             : $err"
    Write-Host "  error_description : $errDesc"
    Write-Host ""
    Write-Host "This is a client ID, redirect URI, or org policy problem." -ForegroundColor Yellow
    Write-Host "The client secret is not involved in this leg." -ForegroundColor Yellow
    return
}

if (-not $code) { throw "No 'code' parameter found in that URL. Paste the full redirect URL including the query string." }

Write-Host ""
Write-Host "LEG 1 PASSED - authorization code received." -ForegroundColor Green
Write-Host "  Client ID and redirect URI are correct, and consent was granted."
if ($gotState -and $gotState -ne $state) {
    Write-Host "  Note: state did not match; you may have pasted a URL from an earlier attempt." -ForegroundColor Yellow
}

Write-Host ""
Write-Host "Leg 2 - token exchange" -ForegroundColor Cyan

$body = "client_id=$([uri]::EscapeDataString($ClientId))" +
        "&client_secret=$([uri]::EscapeDataString($secret))" +
        "&code=$([uri]::EscapeDataString($code))" +
        "&grant_type=authorization_code" +
        "&redirect_uri=$([uri]::EscapeDataString($RedirectUri))"

# GitHub returns HTTP 200 even on failure, and defaults to form-encoded
# responses unless Accept: application/json is sent.
$resp = Invoke-WebRequest -UseBasicParsing -Method Post `
    -Uri "https://github.com/login/oauth/access_token" `
    -Body $body -ContentType "application/x-www-form-urlencoded" `
    -Headers @{ Accept = "application/json" } -SkipHttpErrorCheck

$text = if ($resp.Content -is [byte[]]) { [Text.Encoding]::UTF8.GetString($resp.Content) } else { [string]$resp.Content }
$json = try { $text | ConvertFrom-Json } catch { $null }

Write-Host "  HTTP status  : $($resp.StatusCode)  (GitHub returns 200 even for errors)"
Write-Host "  Content-Type : $($resp.Headers['Content-Type'] -join '')"
Write-Host ""

if ($json -and $json.access_token) {
    Write-Host "LEG 2 PASSED - access token issued." -ForegroundColor Green
    Write-Host "  token prefix  : $($json.access_token.Substring(0,4))..."
    Write-Host "  scope         : $($json.scope)"
    Write-Host "  refresh_token : $(if ($json.refresh_token) { 'yes' } else { 'no' })"
    Write-Host "  expires_in    : $(if ($json.expires_in) { "$($json.expires_in)s" } else { 'never' })"

    Write-Host ""
    Write-Host "Verifying the token against the GitHub MCP server..." -ForegroundColor Cyan
    $mcp = Invoke-WebRequest -UseBasicParsing -Method Post -Uri "https://api.githubcopilot.com/mcp/" `
        -Body '{"jsonrpc":"2.0","id":1,"method":"tools/list","params":{}}' -ContentType "application/json" `
        -Headers @{ Accept = "application/json, text/event-stream"; Authorization = "Bearer $($json.access_token)" } `
        -SkipHttpErrorCheck
    Write-Host "  tools/list status: $($mcp.StatusCode)"

    Write-Host ""
    Write-Host "CONCLUSION: these exact credentials complete the whole flow." -ForegroundColor Green
    Write-Host "If Cowork still fails with them, the fault is in the Teams auth config" -ForegroundColor Green
    Write-Host "or the token store rather than in GitHub or the credentials." -ForegroundColor Green
}
elseif ($json -and $json.error) {
    Write-Host "LEG 2 FAILED" -ForegroundColor Red
    Write-Host "  error             : $($json.error)"
    Write-Host "  error_description : $($json.error_description)"
    Write-Host ""
    switch ($json.error) {
        "incorrect_client_credentials" {
            Write-Host "The client secret is wrong. Generate a new one at" -ForegroundColor Yellow
            Write-Host "https://github.com/settings/developers and paste it into both this test" -ForegroundColor Yellow
            Write-Host "and the Teams developer portal registration." -ForegroundColor Yellow
        }
        "bad_verification_code" {
            Write-Host "The code was already used or expired. Codes are single-use and" -ForegroundColor Yellow
            Write-Host "short-lived - re-run and paste the redirect URL promptly." -ForegroundColor Yellow
        }
        "redirect_uri_mismatch" {
            Write-Host "The redirect URI does not match the OAuth App's Authorization callback URL." -ForegroundColor Yellow
            Write-Host "It must be exactly: $RedirectUri" -ForegroundColor Yellow
        }
        default {
            Write-Host "See https://docs.github.com/apps/managing-oauth-apps/troubleshooting-oauth-app-access-token-request-errors" -ForegroundColor Yellow
        }
    }
}
else {
    Write-Host "LEG 2 - unexpected response:" -ForegroundColor Red
    Write-Host $text
}

$secret = $null
[GC]::Collect()
